### PR TITLE
Avoid bug when query has a limit of 1 but tries to request more than 1 kline

### PR DESCRIPTION
**Pull request by DarkWingMcQuack**
+ bugfix for the bug with a limit of 1
+ cleanup usage of the `in` syntax in `version.sbt`

### CODE REVIEW

**Comment by paoloboni** [comment]
I can't reproduce the the problem mentioned here. Do you mind adding a test to capture the specific case please?
I'm trying with:
```
  "it should fire a single request when expected number of elements returned is within threshold" in new Env {
    withWiremockServer { server =>
      val from      = 1548806400000L
      val to        = 1548866280000L
      val symbol    = "ETHUSDT"
      val interval  = 1.minute.asBinanceInterval.value
      val threshold = 2

      stubInfoEndpoint(server)

      server.stubFor(
        get(s"/api/v1/klines?symbol=$symbol&interval=$interval&startTime=$from&endTime=$to&limit=$threshold")
          .willReturn(
            aResponse()
              .withStatus(200)
              .withBody("""
                          |[
                          |  [1548836400000, "105.13000000", "105.14000000", "105.05000000", "105.09000000", "70.72517000", 1548836459999, "7432.93828700", 45, "36.68194000", "3855.32695710", "0"],
                          |  [1548866279000, "108.39000000", "108.39000000", "108.15000000", "108.22000000", "327.08359000", 1548866339999, "35415.40478090", 129, "163.42355000", "17699.38253540", "0"]
                          |]
              """.stripMargin)
          )
      )

      val config = prepareConfiguration(server)

      val result = BinanceClient(config)
        .use { gw =>
          gw.getKLines(
              KLines(
                symbol = symbol,
                interval = interval.duration,
                startTime = Instant.ofEpochMilli(from),
                endTime = Instant.ofEpochMilli(to),
                limit = threshold
              )
            )
            .compile
            .toList
        }
        .unsafeRunSync()

      val responseFullJson = parse(
        """
          |[
          |  [1548836400000, "105.13000000", "105.14000000", "105.05000000", "105.09000000", "70.72517000", 1548836459999, "7432.93828700", 45, "36.68194000", "3855.32695710", "0"],
          |  [1548866279000, "108.39000000", "108.39000000", "108.15000000", "108.22000000", "327.08359000", 1548866339999, "35415.40478090", 129, "163.42355000", "17699.38253540", "0"]
          |]
        """.stripMargin
      ).right.value
      val expected = responseFullJson.as[List[KLine]].right.value

      result should have size 2
      result should contain theSameElementsInOrderAs expected

      server.verify(getRequestedFor(urlMatching("/api/v1/klines.*")))
    }
  }
```
I must be missing something

**Comment by DarkWingMcQuack** [comment]
Yeah ofc, i will add a testcase

**Comment by DarkWingMcQuack** [comment]
The problem only occurs with `threshold = 1` because than the case
```scala
          case loneElement :: Nil  =>  Stream.emit(loneElement)
```
would be taken without calling `getKlines` recursivly and therefore only one kline is in the result stream

**Comment by DarkWingMcQuack** [comment]
added the testcase which should help understanding the issue

**Comment by paoloboni** [comment]
Makes sense! Thank you :)

**Review by paoloboni — APPROVED** [review]

**Pull request merged**
