### PR TITLE
Make the rate limiter a resource

### LINKED ISSUE #257: Rate limiter leak
Shouldn't this stream be closed along with the client? 

https://github.com/paoloboni/binance-scala-client/blob/master/src/main/scala/io/github/paoloboni/http/ratelimit/RateLimiter.scala#L47

Wonder if we should replace this with https://github.com/SystemFw/upperbound instead?

### PR DESCRIPTION
**Pull request by Swoorup**
Closes #257

I think this is a good idea if you'd like to use libraries like UpperBound in the future. 

Probably related or unrelated to this, I am getting an issue with few HTTP requests being blocked/no longer working after using the api for an extended period of time in between network disconnection but websockets still do work fine however.

### CODE REVIEW

**Comment by benhutchison** [comment]
Out of curiosity, what is UpperBound, I can't find it..?

**Comment by Swoorup** [comment]
> Out of curiosity, what is UpperBound, I can't find it..?

https://systemfw.org/upperbound/#/design 👍🏼

**Comment by benhutchison** [comment]
Thanks. Google query "scala library upperbound typelevel" didn't find it.
Shame on you Google!

**Comment by benhutchison** [comment]
I hope Paolo doesn't mind me hijacking the pr conversation, but have to
remark: love the definition of job that UpperBound uses 'job: F[A]' for
some F[_]

Gone are the days when that would have been a java interface with several
abstract methods that had to be implemented.

**Comment by Swoorup** [comment]
> I hope Paolo doesn't mind me hijacking the pr conversation, but have to remark: love the definition of job that UpperBound uses 'job: F[A]' for some F[_] Gone are the days when that would have been a java interface with several abstract methods that had to be implemented.

Guess I started programming in Scala in the right time, without all the baggage. 😄 ...

**Comment by Swoorup** [comment]
I managed to find the issue, this was happening as the WS stream was never being closed not allowing STTP to clean it up properly. Idk if the queue should be of type `Queue[F, Option[Either[Throwable, T]]` so you could propagate the error back to the consuming queue if you need to.

So hence also fixes https://github.com/paoloboni/binance-scala-client/issues/260

**Comment by paoloboni** [comment]
Thank you @Swoorup! I think using Upperbound is a good idea. Actually it was used in this client, but it wasn't ready at the time the client was migrated to CE3, so had to come up with something else. I see now it's available for CE3 so happy to put it back.

**Pull request merged**
